BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[APP_VResultadoPaciente] (
    [ID] INT NOT NULL,
    [IDFormato] NVARCHAR(1000) NOT NULL,
    [Servicio] NVARCHAR(1000) NOT NULL,
    [Fecha_Str] NVARCHAR(1000) NOT NULL,
    [Hora_Str] NVARCHAR(1000) NOT NULL,
    [Fecha] DATETIME2 NOT NULL,
    [Examen] NVARCHAR(1000) NOT NULL,
    [Importe] DECIMAL(32,16) NOT NULL,
    [Email] NVARCHAR(1000) NOT NULL,
    [RutaPDF] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [APP_VResultadoPaciente_ID_key] UNIQUE NONCLUSTERED ([ID])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
